const major = 'major'
const wands = 'wands'
const pentacles = 'pentacles'
const cups = 'cups'
const swords = 'swords'
export default [
    {
        id: 0,
        type: major,
        name: 'The Fool',
        img: 'https://upload.wikimedia.org/wikipedia/en/9/90/RWS_Tarot_00_Fool.jpg',
    },
    {
        id: 1,
        type: major,
        name: 'The Magician',
        img: 'https://upload.wikimedia.org/wikipedia/en/d/de/RWS_Tarot_01_Magician.jpg',
    },
    {
        id: 2,
        type: major,
        name: 'The High Priestess',
        img: 'https://upload.wikimedia.org/wikipedia/en/8/88/RWS_Tarot_02_High_Priestess.jpg',
    },
    {
        id: 3,
        type: major,
        name: 'The Empress',
        img: 'https://upload.wikimedia.org/wikipedia/en/d/d2/RWS_Tarot_03_Empress.jpg',
    },
    {
        id: 4,
        type: major,
        name: 'The Emperor',
        img: 'https://upload.wikimedia.org/wikipedia/en/c/c3/RWS_Tarot_04_Emperor.jpg',
    },
    {
        id: 5,
        type: major,
        name: 'The Hierophant',
        img: 'https://upload.wikimedia.org/wikipedia/en/8/8d/RWS_Tarot_05_Hierophant.jpg',
    },
    {
        id: 6,
        type: major,
        name: 'The Lovers',
        img: 'https://upload.wikimedia.org/wikipedia/en/d/db/RWS_Tarot_06_Lovers.jpg',
    },
    {
        id: 7,
        type: major,
        name: 'The Chariot',
        img: 'https://upload.wikimedia.org/wikipedia/en/9/9b/RWS_Tarot_07_Chariot.jpg',
    },
    {
        id: 8,
        type: major,
        name: 'Strength',
        img: 'https://upload.wikimedia.org/wikipedia/en/f/f5/RWS_Tarot_08_Strength.jpg',
    },
    {
        id: 9,
        type: major,
        name: 'The Hermit',
        img: 'https://upload.wikimedia.org/wikipedia/en/4/4d/RWS_Tarot_09_Hermit.jpg',
    },
    {
        id: 10,
        type: major,
        name: 'Wheel of Fortune',
        img: 'https://upload.wikimedia.org/wikipedia/en/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg',
    },
    {
        id: 11,
        type: major,
        name: 'Strength',
        img: 'https://upload.wikimedia.org/wikipedia/en/f/f5/RWS_Tarot_08_Strength.jpg',
    },
    {
        id: 12,
        type: major,
        name: 'The Hanged Man',
        img: 'https://upload.wikimedia.org/wikipedia/en/2/2b/RWS_Tarot_12_Hanged_Man.jpg',
    },
    {
        id: 13,
        type: major,
        name: 'Death',
        img: 'https://upload.wikimedia.org/wikipedia/en/d/d7/RWS_Tarot_13_Death.jpg',
    },
    {
        id: 14,
        type: major,
        name: 'Temperance',
        img: 'https://upload.wikimedia.org/wikipedia/en/f/f8/RWS_Tarot_14_Temperance.jpg',
    },
    {
        id: 15,
        type: major,
        name: 'The Devil',
        img: 'https://upload.wikimedia.org/wikipedia/en/5/55/RWS_Tarot_15_Devil.jpg',
    },
    {
        id: 16,
        type: major,
        name: 'The Tower',
        img: 'https://upload.wikimedia.org/wikipedia/en/5/53/RWS_Tarot_16_Tower.jpg',
    },
    {
        id: 17,
        type: major,
        name: 'The Star',
        img: 'https://upload.wikimedia.org/wikipedia/en/d/db/RWS_Tarot_17_Star.jpg',
    },
    {
        id: 18,
        type: major,
        name: 'The Moon',
        img: 'https://upload.wikimedia.org/wikipedia/en/7/7f/RWS_Tarot_18_Moon.jpg',
    },
    {
        id: 19,
        type: major,
        name: 'The Sun',
        img: 'https://upload.wikimedia.org/wikipedia/en/1/17/RWS_Tarot_19_Sun.jpg',
    },
    {
        id: 20,
        type: major,
        name: 'Judgement',
        img: 'https://upload.wikimedia.org/wikipedia/en/d/dd/RWS_Tarot_20_Judgement.jpg',
    },
    {
        id: 21,
        type: major,
        name: 'The World',
        img: 'https://upload.wikimedia.org/wikipedia/en/f/ff/RWS_Tarot_21_World.jpg',
    },
    {
        id: 22,
        type: wands,
        name: 'Ace of Wands',
        img: 'https://upload.wikimedia.org/wikipedia/en/1/11/Wands01.jpg',
    },
    {
        id: 23,
        type: wands,
        name: 'Two of Wands',
        img: 'https://upload.wikimedia.org/wikipedia/en/0/0f/Wands02.jpg',
    },
    {
        id: 24,
        type: wands,
        name: 'Three of Wands',
        img: 'https://upload.wikimedia.org/wikipedia/en/f/ff/Wands03.jpg',
    },
    {
        id: 25,
        type: wands,
        name: 'Four of Wands',
        img: 'https://upload.wikimedia.org/wikipedia/en/a/a4/Wands04.jpg',
    },
    {
        id: 26,
        type: wands,
        name: 'Five of Wands',
        img: 'https://upload.wikimedia.org/wikipedia/en/9/9d/Wands05.jpg',
    },
    {
        id: 27,
        type: wands,
        name: 'Six of Wands',
        img: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Wands06.jpg',
    },
    {
        id: 28,
        type: wands,
        name: 'Seven of Wands',
        img: 'https://upload.wikimedia.org/wikipedia/en/e/e4/Wands07.jpg',
    },
    {
        id: 29,
        type: wands,
        name: 'Eight of Wands',
        img: 'https://upload.wikimedia.org/wikipedia/en/6/6b/Wands08.jpg',
    },
    {
        id: 30,
        type: wands,
        name: 'Nine of Wands',
        img: 'https://upload.wikimedia.org/wikipedia/en/e/e7/Wands09.jpg',
    },
    {
        id: 31,
        type: wands,
        name: 'Ten of Wands',
        img: 'https://upload.wikimedia.org/wikipedia/en/0/0b/Wands10.jpg',
    },
    {
        id: 32,
        type: wands,
        name: 'Page of Wands',
        img: 'https://upload.wikimedia.org/wikipedia/en/6/6a/Wands11.jpg',
    },
    {
        id: 33,
        type: wands,
        name: 'Knight of Wands',
        img: 'https://upload.wikimedia.org/wikipedia/en/1/16/Wands12.jpg',
    },
    {
        id: 34,
        type: wands,
        name: 'Queen of Wands',
        img: 'https://upload.wikimedia.org/wikipedia/en/0/0d/Wands13.jpg',
    },
    {
        id: 35,
        type: wands,
        name: 'King of Wands',
        img: 'https://upload.wikimedia.org/wikipedia/en/c/ce/Wands14.jpg',
    },
    {
        id: 36,
        type: pentacles,
        name: 'Ace of Pentacles',
        img: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Pents01.jpg',
    },
    {
        id: 37,
        type: pentacles,
        name: 'Two of Pentacles',
        img: 'https://upload.wikimedia.org/wikipedia/en/9/9f/Pents02.jpg',
    },
    {
        id: 38,
        type: pentacles,
        name: 'Three of Pentacles',
        img: 'https://upload.wikimedia.org/wikipedia/en/4/42/Pents03.jpg',
    },
    {
        id: 39,
        type: pentacles,
        name: 'Four of Pentacles',
        img: 'https://upload.wikimedia.org/wikipedia/en/3/35/Pents04.jpg',
    },
    {
        id: 40,
        type: pentacles,
        name: 'Five of Pentacles',
        img: 'https://upload.wikimedia.org/wikipedia/en/9/96/Pents05.jpg',
    },
    {
        id: 41,
        type: pentacles,
        name: 'Six of Pentacles',
        img: 'https://upload.wikimedia.org/wikipedia/en/a/a6/Pents06.jpg',
    },
    {
        id: 42,
        type: pentacles,
        name: 'Seven of Pentacles',
        img: 'https://upload.wikimedia.org/wikipedia/en/6/6a/Pents07.jpg',
    },
    {
        id: 43,
        type: pentacles,
        name: 'Eight of Pentacles',
        img: 'https://upload.wikimedia.org/wikipedia/en/4/49/Pents08.jpg',
    },
    {
        id: 44,
        type: pentacles,
        name: 'Nine of Pentacles',
        img: 'https://upload.wikimedia.org/wikipedia/en/f/f0/Pents09.jpg',
    },
    {
        id: 45,
        type: pentacles,
        name: 'Ten of Pentacles',
        img: 'https://upload.wikimedia.org/wikipedia/en/4/42/Pents10.jpg',
    },
    {
        id: 46,
        type: pentacles,
        name: 'Page of Pentacles',
        img: 'https://upload.wikimedia.org/wikipedia/en/e/ec/Pents11.jpg',
    },
    {
        id: 47,
        type: pentacles,
        name: 'Knight of Pentacles',
        img: 'https://upload.wikimedia.org/wikipedia/en/d/d5/Pents12.jpg',
    },
    {
        id: 48,
        type: pentacles,
        name: 'Queen of Pentacles',
        img: 'https://upload.wikimedia.org/wikipedia/en/8/88/Pents13.jpg',
    },
    {
        id: 49,
        type: pentacles,
        name: 'King of Pentacles',
        img: 'https://upload.wikimedia.org/wikipedia/en/1/1c/Pents14.jpg',
    },
    {
        id: 50,
        type: cups,
        name: 'Ace of Cups',
        img: 'https://upload.wikimedia.org/wikipedia/en/3/36/Cups01.jpg',
    },
    {
        id: 51,
        type: cups,
        name: 'Two of Cups',
        img: 'https://upload.wikimedia.org/wikipedia/en/f/f8/Cups02.jpg',
    },
    {
        id: 52,
        type: cups,
        name: 'Three of Cups',
        img: 'https://upload.wikimedia.org/wikipedia/en/7/7a/Cups03.jpg',
    },
    {
        id: 53,
        type: cups,
        name: 'Four of Cups',
        img: 'https://upload.wikimedia.org/wikipedia/en/3/35/Cups04.jpg',
    },
    {
        id: 54,
        type: cups,
        name: 'Five of Cups',
        img: 'https://upload.wikimedia.org/wikipedia/en/d/d7/Cups05.jpg',
    },
    {
        id: 55,
        type: cups,
        name: 'Six of Cups',
        img: 'https://upload.wikimedia.org/wikipedia/en/1/17/Cups06.jpg',
    },
    {
        id: 56,
        type: cups,
        name: 'Seven of Cups',
        img: 'https://upload.wikimedia.org/wikipedia/en/a/ae/Cups07.jpg',
    },
    {
        id: 57,
        type: cups,
        name: 'Eight of Cups',
        img: 'https://upload.wikimedia.org/wikipedia/en/6/60/Cups08.jpg',
    },
    {
        id: 58,
        type: cups,
        name: 'Nine of Cups',
        img: 'https://upload.wikimedia.org/wikipedia/en/2/24/Cups09.jpg',
    },
    {
        id: 59,
        type: cups,
        name: 'Ten of Cups',
        img: 'https://upload.wikimedia.org/wikipedia/en/8/84/Cups10.jpg',
    },
    {
        id: 60,
        type: cups,
        name: 'Page of Cups',
        img: 'https://upload.wikimedia.org/wikipedia/en/a/ad/Cups11.jpg',
    },
    {
        id: 61,
        type: cups,
        name: 'Knight of Cups',
        img: 'https://upload.wikimedia.org/wikipedia/en/f/fa/Cups12.jpg',
    },
    {
        id: 62,
        type: cups,
        name: 'Queen of Cups',
        img: 'https://upload.wikimedia.org/wikipedia/en/6/62/Cups13.jpg',
    },
    {
        id: 63,
        type: cups,
        name: 'King of Cups',
        img: 'https://upload.wikimedia.org/wikipedia/en/0/04/Cups14.jpg',
    },
    {
        id: 64,
        type: swords,
        name: 'Ace of Swords',
        img: 'https://upload.wikimedia.org/wikipedia/en/1/1a/Swords01.jpg',
    },
    {
        id: 65,
        type: swords,
        name: 'Two of Swords',
        img: 'https://upload.wikimedia.org/wikipedia/en/9/9e/Swords02.jpg',
    },
    {
        id: 66,
        type: swords,
        name: 'Three of Swords',
        img: 'https://upload.wikimedia.org/wikipedia/en/0/02/Swords03.jpg',
    },
    {
        id: 67,
        type: swords,
        name: 'Four of Swords',
        img: 'https://upload.wikimedia.org/wikipedia/en/b/bf/Swords04.jpg',
    },
    {
        id: 68,
        type: swords,
        name: 'Five of Swords',
        img: 'https://upload.wikimedia.org/wikipedia/en/2/23/Swords05.jpg',
    },
    {
        id: 69,
        type: swords,
        name: 'Six of Swords',
        img: 'https://upload.wikimedia.org/wikipedia/en/2/29/Swords06.jpg',
    },
    {
        id: 70,
        type: swords,
        name: 'Seven of Swords',
        img: 'https://upload.wikimedia.org/wikipedia/en/3/34/Swords07.jpg',
    },
    {
        id: 71,
        type: swords,
        name: 'Eight of Swords',
        img: 'https://upload.wikimedia.org/wikipedia/en/a/a7/Swords08.jpg',
    },
    {
        id: 72,
        type: swords,
        name: 'Nine of Swords',
        img: 'https://upload.wikimedia.org/wikipedia/en/2/2f/Swords09.jpg',
    },
    {
        id: 73,
        type: swords,
        name: 'Ten of Swords',
        img: 'https://upload.wikimedia.org/wikipedia/commons/5/5f/10swords.jpg',
    },
    {
        id: 74,
        type: swords,
        name: 'Page of Swords',
        img: 'https://upload.wikimedia.org/wikipedia/en/4/4c/Swords11.jpg',
    },
    {
        id: 75,
        type: swords,
        name: 'Knight of Swords',
        img: 'https://upload.wikimedia.org/wikipedia/en/b/b0/Swords12.jpg',
    },
    {
        id: 76,
        type: swords,
        name: 'Queen of Swords',
        img: 'https://upload.wikimedia.org/wikipedia/en/d/d4/Swords13.jpg',
    },
    {
        id: 77,
        type: swords,
        name: 'King of Swords',
        img: 'https://upload.wikimedia.org/wikipedia/en/3/33/Swords14.jpg',
    },
];
